import { ObjectId } from 'mongodb';
import db from '@/config/DBHelpler';
import Menus from '@/model/Menus';

const menus = [
  {
    _id: ObjectId('5e7f066587e2af428a868a4e'),
    title: '内容管理',
    name: 'content_management',
    path: '/content',
    component: '/components/main',
    hideInBread: true,
    hideInMenu: true,
    notCache: true,
    icon: 'md-albums',
    sort: '0',
    link: '',
    redirect: '',
    type: 'menu',
    expand: true,
    operations: [],
    children: [
      {
        title: '文章管理',
        name: 'article_management',
        path: '/content/index',
        component: '/view/content/index',
        hideInBread: false,
        hideInMenu: false,
        notCache: false,
        icon: '',
        sort: '10',
        link: '',
        redirect: '',
        type: 'menu',
        expand: true,
        _id: ObjectId('60e115aba6e6e161725caefd'),
        operations: [
          {
            name: '获取文章列表',
            type: 'api',
            method: 'get',
            path: '/public/list',
            regmark: '',
            _id: ObjectId('63ff0b9e38adfe9c92d53b8a'),
          },
          {
            name: '删除文章',
            type: 'api',
            method: 'post',
            path: '/admin/content/delete',
            regmark: '',
            _id: ObjectId('63ff0b9e38adfe9c92d53b8b'),
          },
          {
            name: '更新文章属性',
            type: 'api',
            method: 'post',
            path: '/admin/content/updateId',
            regmark: '',
            _id: ObjectId('63ff0bc638adfe9c92d53baa'),
          },
          {
            name: '批量更新',
            type: 'api',
            method: 'post',
            path: '/admin/content/updatePostSettings',
            regmark: '',
            _id: ObjectId('63ff0c0238adfe9c92d53bcb'),
          },
        ],
        children: [],
      },
      {
        title: '标签管理',
        name: 'tags_management',
        path: '/content/tags',
        component: '/view/content/tags',
        hideInBread: true,
        hideInMenu: true,
        notCache: true,
        icon: '',
        sort: '20',
        link: '',
        redirect: '',
        type: 'menu',
        expand: true,
        _id: ObjectId('60e113a7a6e6e171b85cae5a'),
        operations: [
          {
            name: '读取标签列表',
            type: 'api',
            method: 'get',
            path: '/admin/getTags',
            regmark: '',
            _id: ObjectId('60e113a7a6e6e1d1505cae5b'),
          },
          {
            name: '删除标签',
            type: 'api',
            method: 'get',
            path: '/admin/removeTag',
            regmark: '',
            _id: ObjectId('63ff0b1338adfe9c92d53b45'),
          },
          {
            name: '更新标签',
            type: 'api',
            method: 'post',
            path: '/admin/editTag',
            regmark: '',
            _id: ObjectId('63ff0c5238adfe9c92d53beb'),
          },
        ],
        children: [],
      },
    ],
  },

  {
    _id: ObjectId('5e7f0f6087e2aff7ab868a56'),
    title: '内容安全',
    name: 'comments_management',
    path: '/comments',
    component: '/components/main',
    hideInBread: true,
    hideInMenu: false,
    notCache: true,
    icon: 'ios-umbrella',
    sort: '0',
    link: '',
    redirect: '',
    type: 'menu',
    expand: true,
    operations: [],
    children: [
      {
        title: '评论管理',
        name: 'comments_list',
        path: '/comments/index',
        component: '/view/comments/index',
        hideInBread: true,
        hideInMenu: true,
        notCache: true,
        icon: 'ios-chatbubbles',
        sort: '0',
        link: '',
        redirect: '',
        type: 'menu',
        expand: true,
        _id: ObjectId('5e7f0f9a87e2afa689868a57'),
        children: [],
        operations: [
          {
            name: '获取评论',
            type: 'api',
            method: 'get',
            path: '/admin/getComments',
            regmark: '',
            _id: ObjectId('5ea5087fd6b70c3612218368'),
          },
          {
            name: '更新评论',
            type: 'api',
            method: 'post',
            path: '/admin/updateCommentsBatch',
            regmark: '',
            _id: ObjectId('5ea5087fd6b70cafce218369'),
          },
          {
            name: '删除评论',
            type: 'api',
            method: 'post',
            path: '/admin/deleteComments',
            regmark: '',
            _id: ObjectId('5ea5087fd6b70c1d8d21836a'),
          },
        ],
      },
    ],
  },

  {
    _id: ObjectId('5e7f0fde87e2afd6c2868a58'),
    title: '用户管理',
    name: 'user',
    path: '/user',
    component: '/components/main',
    hideInBread: true,
    hideInMenu: false,
    notCache: true,
    icon: 'md-albums',
    sort: '0',
    link: '',
    redirect: '',
    type: 'menu',
    expand: true,
    operations: [],
    children: [
      {
        title: '用户管理',
        name: 'user_management',
        path: '/user/index',
        component: '/view/user/index',
        hideInBread: true,
        hideInMenu: true,
        notCache: true,
        icon: 'ios-people',
        sort: '0',
        link: '',
        redirect: '',
        type: 'menu',
        expand: true,
        _id: ObjectId('616cf53f848d26a4413d29f6'),
        operations: [
          {
            name: '删除用户',
            type: 'api',
            method: 'post',
            path: '/admin/deleteUser',
            regmark: '',
            _id: ObjectId('63ff0df002632dad049f8772'),
          },
          {
            name: '批量更新用户',
            type: 'api',
            method: 'post',
            path: '/admin/updateUserSettings',
            regmark: '',
            _id: ObjectId('63ff0df002632dad049f8773'),
          },
          {
            name: '更新用户',
            type: 'api',
            method: 'post',
            path: '/admin/updateUser',
            regmark: '',
            _id: ObjectId('63ff0df002632dad049f8774'),
          },
          {
            name: '查询是否重名',
            type: 'api',
            method: 'get',
            path: '/admin/checkname',
            regmark: '',
            _id: ObjectId('63ff0df002632dad049f8775'),
          },
          {
            name: '获取用户列表',
            type: 'api',
            method: 'get',
            path: '/admin/users',
            regmark: '',
            _id: ObjectId('63ff0df002632dad049f8776'),
          },
          {
            name: '添加用户',
            type: 'api',
            method: 'post',
            path: '/admin/addUser',
            regmark: '',
            _id: ObjectId('63ff4c7a09f96625fc42c89a'),
          },
        ],
        children: [],
      },
    ],
  },

  {
    _id: ObjectId('5e7f105b87e2af201b868a5a'),
    title: '菜单管理',
    name: 'menu',
    path: '/menu',
    component: '/components/main',
    hideInBread: true,
    hideInMenu: false,
    notCache: true,
    icon: 'md-settings',
    sort: '0',
    link: '',
    redirect: '',
    type: 'menu',
    expand: true,
    operations: [],
    children: [
      {
        title: '菜单管理',
        name: 'menu_management',
        path: '/menu/index',
        component: '/view/menu/index',
        hideInBread: true,
        hideInMenu: true,
        notCache: true,
        icon: 'ios-menu',
        sort: '0',
        link: '',
        redirect: '',
        type: 'menu',
        expand: true,
        _id: ObjectId('5e7f10ba87e2af4114868a5b'),
        children: [],
        operations: [
          {
            name: '新增菜单',
            type: 'api',
            method: 'post',
            path: '/admin/addMenu',
            regmark: '',
            _id: ObjectId('5ea50638d6b70c2c6b21835a'),
          },
          {
            name: '获取菜单',
            type: 'api',
            method: 'get',
            path: '/admin/getMenu',
            regmark: '',
            _id: ObjectId('5ea50638d6b70c507021835b'),
          },
          {
            name: '更新菜单',
            type: 'api',
            method: 'post',
            path: '/admin/updateMenu',
            regmark: '',
            _id: ObjectId('5ea50638d6b70c4b8021835c'),
          },
          {
            name: '删除菜单',
            type: 'api',
            method: 'post',
            path: '/admin/deleteMenu',
            regmark: '',
            _id: ObjectId('5ea50638d6b70c5aba21835d'),
          },
        ],
      },
    ],
  },

  {
    _id: ObjectId('5e7f10f887e2af0042868a5c'),
    title: '权限管理',
    name: 'roles',
    path: '/roles',
    component: '/components/main',
    hideInBread: true,
    hideInMenu: true,
    notCache: true,
    icon: 'md-checkbox',
    sort: '0',
    link: '',
    redirect: '',
    type: 'menu',
    expand: true,
    operations: [],
    children: [
      {
        title: '角色权限',
        name: 'roles_management',
        path: '/roles/index',
        component: '/view/roles/index',
        hideInBread: true,
        hideInMenu: true,
        notCache: true,
        icon: 'md-key',
        sort: '0',
        link: '',
        redirect: '',
        type: 'menu',
        expand: true,
        _id: ObjectId('5e7f115d87e2af8496868a5d'),
        children: [],
        operations: [
          {
            name: '新增角色',
            type: 'api',
            method: 'post',
            path: '/admin/addRole',
            regmark: '',
            _id: ObjectId('5ea506d7d6b70c205321835f'),
          },
          {
            name: '获取角色',
            type: 'api',
            method: 'get',
            path: '/admin/getRoles',
            regmark: '',
            _id: ObjectId('5ea506d7d6b70c362a218360'),
          },
          {
            name: '获取角色名',
            type: 'api',
            method: 'get',
            path: '/admin/getRolesNames',
            regmark: '',
            _id: ObjectId('5ea506d7d6b70c9883218361'),
          },
          {
            name: '更新角色',
            type: 'api',
            method: 'post',
            path: '/admin/updateRole',
            regmark: '',
            _id: ObjectId('5ea506d7d6b70c4138218362'),
          },
          {
            name: '删除角色',
            type: 'api',
            method: 'post',
            path: '/admin/deleteRole',
            regmark: '',
            _id: ObjectId('5ea506d7d6b70cd568218363'),
          },
        ],
      },
      {
        title: '首页可视化',
        name: 'Main',
        path: '/components',
        component: 'componentn',
        hideInBread: false,
        hideInMenu: false,
        notCache: false,
        icon: '',
        sort: '0',
        link: '',
        redirect: '',
        type: 'resouce',
        expand: true,
        _id: ObjectId('6098fe4be24abdfe9b992878'),
        operations: [
          {
            name: '统计数据',
            type: 'api',
            method: 'get',
            path: '/admin/getstat',
            regmark: '',
            _id: ObjectId('6098feaee24abd6fd6992880'),
          },
        ],
        children: [],
      },
    ],
  },

  {
    _id: ObjectId('5e7f118187e2af3a4b868a5e'),
    title: '系统管理',
    name: 'system',
    path: '/system',
    component: '/components/main',
    hideInBread: true,
    hideInMenu: false,
    notCache: true,
    icon: 'md-settings',
    sort: '0',
    link: '',
    redirect: '',
    type: 'menu',
    expand: true,
    operations: [],
    children: [
      {
        title: '错误日志',
        name: 'logs_check',
        path: '/system/index',
        component: '/view/logs/index',
        hideInBread: true,
        hideInMenu: true,
        notCache: true,
        icon: 'ios-bug',
        sort: '0',
        link: '',
        redirect: '',
        type: 'menu',
        expand: true,
        _id: ObjectId('5e7f11d687e2af6a7f868a5f'),
        children: [],
        operations: [
          {
            name: '获取错误日志',
            type: 'api',
            method: 'get',
            path: '/admin/getError',
            regmark: '',
            _id: ObjectId('5ea50704d6b70c5638218365'),
          },
          {
            name: '删除错误日志',
            type: 'api',
            method: 'post',
            path: '/admin/deleteError',
            regmark: '',
            _id: ObjectId('5ea50704d6b70c803f218366'),
          },
          {
            name: '获取错误日志统计',
            type: 'api',
            method: 'get',
            path: '/admin/getErrorStats',
            regmark: '',
            _id: ObjectId('64004737e29d737e0a55fcaa'),
          },
        ],
      },
    ],
  },

  {
    _id: ObjectId('5e7f220a87e2afedc7868a65'),
    title: '项目文档',
    name: 'doc',
    path: '/',
    component: '',
    hideInBread: false,
    hideInMenu: false,
    notCache: true,
    icon: 'ios-folder',
    sort: '0',
    link: '',
    redirect: '',
    type: 'menu',
    expand: true,
    operations: [],
    children: [
      {
        title: 'iview-admin文档',
        name: '',
        path: '/iview',
        component: '',
        hideInBread: false,
        hideInMenu: false,
        notCache: false,
        icon: 'ios-book',
        sort: '0',
        link: 'https://lison16.github.io/iview-admin-doc/#/',
        redirect: '',
        type: 'link',
        expand: true,
        _id: ObjectId('5e7f226787e2aff47c868a67'),
        operations: [],
        children: [],
      },
      {
        title: '接口文档',
        name: '',
        path: '/api',
        component: '',
        hideInBread: false,
        hideInMenu: false,
        notCache: false,
        icon: 'ios-cube',
        sort: '0',
        link: 'https://doc.toimc.com/web/#/2?page_id=42',
        redirect: '',
        type: 'link',
        expand: true,
        _id: ObjectId('5e7f226787e2af21dd868a68'),
        operations: [],
        children: [],
      },
    ],
  },

  {
    _id: ObjectId('5e7f232087e2af64ad868a69'),
    title: '社区信息',
    name: 'join_page',
    path: '/join/join_page',
    component: '/view/join-page',
    hideInBread: true,
    hideInMenu: true,
    notCache: true,
    icon: '_qq',
    sort: '0',
    link: '',
    redirect: '',
    type: 'menu',
    expand: true,
    operations: [],
    children: [],
  },

  {
    _id: ObjectId('5ea5bb09d6b70c730f21836b'),
    title: '社区front',
    name: 'front',
    path: '/',
    component: '',
    hideInBread: false,
    hideInMenu: false,
    notCache: true,
    icon: '',
    sort: '50',
    link: '',
    redirect: '',
    type: 'menu',
    expand: true,
    operations: [],
    children: [
      {
        title: '公共',
        name: 'common',
        path: '/common',
        component: '',
        hideInBread: false,
        hideInMenu: false,
        notCache: true,
        icon: '',
        sort: '0',
        link: '',
        redirect: '',
        type: 'resouce',
        expand: true,
        _id: ObjectId('5ea5bdc4d6b70c8aae2183de'),
        operations: [
          {
            name: '获取验证码',
            type: 'api',
            method: 'get',
            path: '/public/getCaptcha',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c25362183df'),
          },
          {
            name: '忘记密码',
            type: 'api',
            method: 'post',
            path: '/login/forget',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70cd8c92183e0'),
          },
          {
            name: '登录',
            type: 'api',
            method: 'post',
            path: '/login/login',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70ced092183e1'),
          },
          {
            name: '注册',
            type: 'api',
            method: 'post',
            path: '/login/reg',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c33f72183e2'),
          },
          {
            name: '重置密码',
            type: 'api',
            method: 'post',
            path: '/login/reset',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c84a12183e3'),
          },
        ],
        children: [],
      },
      {
        title: '用户',
        name: 'user',
        path: '/user',
        component: '',
        hideInBread: false,
        hideInMenu: false,
        notCache: true,
        icon: '',
        sort: '0',
        link: '',
        redirect: '',
        type: 'resouce',
        expand: true,
        _id: ObjectId('5ea5bdc4d6b70caf472183e4'),
        operations: [
          {
            name: '用户签到',
            type: 'api',
            method: 'get',
            path: '/user/fav',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c1e492183e5'),
          },
          {
            name: '更新用户基本资料',
            type: 'api',
            method: 'post',
            path: '/user/basic',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70cafbe2183e6'),
          },
          {
            name: '确认修改用户名',
            type: 'api',
            method: 'get',
            path: '/public/resetEmail',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70ca45b2183e7'),
          },
          {
            name: '修改用户密码',
            type: 'api',
            method: 'post',
            path: '/user/changePassword',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c5a622183e8'),
          },
          {
            name: '设置收藏 & 取消收藏',
            type: 'api',
            method: 'get',
            path: '/user/setCollect',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c4b222183e9'),
          },
          {
            name: '获取收藏列表',
            type: 'api',
            method: 'get',
            path: '/user/collect',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c02e52183ea'),
          },
          {
            name: '获取发表的文章列表',
            type: 'api',
            method: 'get',
            path: '/user/post',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70cf6bd2183eb'),
          },
          {
            name: '获取用户最近的发表文章列表',
            type: 'api',
            method: 'get',
            path: '/public/latestPost',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c52122183ec'),
          },
          {
            name: '删除指定文章列表',
            type: 'api',
            method: 'get',
            path: '/user/deletePost',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70cf32f2183ed'),
          },
          {
            name: '获取用户的基本信息',
            type: 'api',
            method: 'get',
            path: '/public/info',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c130f2183ee'),
          },
          {
            name: '获取用户最近评论列表',
            type: 'api',
            method: 'get',
            path: '/public/latestComment',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c70f22183ef'),
          },
          {
            name: '获取用户未读消息',
            type: 'api',
            method: 'get',
            path: '/user/getmsg',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c533c2183f0'),
          },
          {
            name: '设置用户未读消息',
            type: 'api',
            method: 'get',
            path: '/user/setmsg',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c15032183f1'),
          },
          {
            name: '使用优惠券',
            type: 'api',
            method: 'post',
            path: '/coupon/check',
            regmark: '',
            _id: ObjectId('60d05892b8f1837efe13264e'),
          },
          {
            name: '获取用户当前面的权限',
            type: 'api',
            method: 'post',
            path: '/user/wxauth',
            regmark: '',
            _id: ObjectId('60d05892b8f183c1f413264f'),
          },
          {
            name: '添加意见反馈',
            type: 'api',
            method: 'post',
            path: '/user/survey',
            regmark: '',
            _id: ObjectId('60d05892b8f183832c132650'),
          },
          {
            name: '获取动态菜单',
            type: 'api',
            method: 'get',
            path: '/admin/getRoutes',
            regmark: '',
            _id: ObjectId('63ff01fa38adfe9c92d539d0'),
          },
        ],
        children: [],
      },
      {
        title: '内容',
        name: 'content',
        path: '/content',
        component: '',
        hideInBread: false,
        hideInMenu: false,
        notCache: true,
        icon: '',
        sort: '0',
        link: '',
        redirect: '',
        type: 'resouce',
        expand: true,
        _id: ObjectId('5ea5bdc4d6b70c46902183f2'),
        operations: [
          {
            name: '友情链接',
            type: 'api',
            method: 'get',
            path: '/public/links',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c46492183f6'),
          },
          {
            name: '图片上传接口',
            type: 'api',
            method: 'post',
            path: '/content/upload',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c26582183f7'),
          },
          {
            name: '发贴接口',
            type: 'api',
            method: 'post',
            path: '/content/add',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c24962183f8'),
          },
          {
            name: '获取文章详情',
            type: 'api',
            method: 'get',
            path: '/public/content/detail',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c20512183f9'),
          },
          {
            name: '更新文章，编辑帖子',
            type: 'api',
            method: 'post',
            path: '/content/update',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c53112183fa'),
          },
        ],
        children: [],
      },
      {
        title: '评论',
        name: 'comments',
        path: '/comments',
        component: '',
        hideInBread: false,
        hideInMenu: false,
        notCache: true,
        icon: '',
        sort: '0',
        link: '',
        redirect: '',
        type: 'resouce',
        expand: true,
        _id: ObjectId('5ea5bdc4d6b70c7d1d2183fb'),
        operations: [
          {
            name: '获取文章中的评论列表',
            type: 'api',
            method: 'get',
            path: '/public/comments',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70ced382183fc'),
          },
          {
            name: '添加评论',
            type: 'api',
            method: 'post',
            path: '/comments/reply',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c09812183fd'),
          },
          {
            name: '更新评论',
            type: 'api',
            method: 'post',
            path: '/comments/update',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c7bb42183fe'),
          },
          {
            name: '采纳最佳评论',
            type: 'api',
            method: 'get',
            path: '/comments/accept',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c08b82183ff'),
          },
          {
            name: '设置点赞',
            type: 'api',
            method: 'get',
            path: '/comments/hands',
            regmark: '',
            _id: ObjectId('5ea5bdc4d6b70c7f54218400'),
          },
        ],
        children: [],
      },
    ],
  },

  {
    _id: ObjectId('60d0632dbde6661f002b97ae'),
    title: '优惠券',
    name: 'CouponIndex',
    path: '/coupon',
    component: '/coupon/index',
    hideInBread: false,
    hideInMenu: false,
    notCache: false,
    icon: '',
    sort: '100',
    link: '',
    redirect: '',
    type: 'menu',
    expand: true,
    operations: [
      {
        name: '新增coupon',
        type: 'api',
        method: 'post',
        path: '/admin/genCoupon',
        regmark: '',
        _id: ObjectId('60d0637dbde66611142b97ce'),
      },
      {
        name: '验证coupon',
        type: 'api',
        method: 'post',
        path: '/coupon/check',
        regmark: '',
        _id: ObjectId('60d0637dbde66667822b97cf'),
      },
      {
        name: '更新coupon',
        type: 'api',
        method: 'post',
        path: '/admin/updateCoupon',
        regmark: '',
        _id: ObjectId('60d0637dbde66658412b97d0'),
      },
    ],
    children: [],
  },
];

export default async () => {
  await db.connection.dropCollection('menus');
  await Menus.createCollection();
  try {
    await Menus.insertMany(menus);
  } catch (error) {
    console.log('Menus数据写入失败', error);
  }
};
